### ISSUE TITLE
Revisão e finalização da Introdução do livro

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#102]
@hjbortol preciso que você edite o último parágrafo incluindo as referências ou adequando o texto.

@estelanunes  e @cydara , precisamos de uma leitura cuidadosa da introdução. Vocês também podem fazer adições ou subtrações no texto. :-)

https://www.umlivroaberto.com/livro/doku.php?id=cap0:navega

**Comment by hjbortol** [comment]
Caros,

Com o estilo de redação atual, achei melhor deixar o final da introdução apenas o que vai ficar para o Volume 2, sem as explicações. 

O que acham?

**Comment by estelanunes** [comment]
Estou trabalhando nisso agora.

**Comment by estelanunes** [comment]
Caros, segue até onde fui. 
[Introducao_LET.docx](https://github.com/UmLivroAberto/livro/files/441400/Introducao_LET.docx)

**Comment by estelanunes** [comment]
Consegui rever todo o texto. **Ficou faltando colocar algumas referências. Acho que  @hjbortol  seria a pessoa ideial para fazê-lo. ;)** Vejam o que acham.  
  ##[Introducao_LET.docx](https://github.com/UmLivroAberto/livro/files/441427/Introducao_LET.docx)

**Comment by hjbortol** [comment]
Caros, posso tentar incluir as referências, mas acho que só consigo trabalhar na introdução amanhã a tarde, pois as aulas do segundo semestre na UFF iniciam amanhã (dou aulas das 7 h às 11 h e estou terminando de preparar o que vou usar durante a semana)!
