### ISSUE TITLE
Revisão final do livro do Aluno em pdf (sem a Lição 5)

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#103]
Gostaria especialmente que conferissem:
1. se as últimas alterações de vocês estão no livro. Eu fui pegando o que vi de novo na Plataforma, mas posso ter perdido alguma coisa.
2.  se as referências às cores estão adequadas (tive que alterar algumas para coincidir com a paleta de cores e posso ter feito besteira)
3. se as figuras estão bem feitas, se estão no local correto etc.
4. quaisquer outras modificações estéticas são bem-vindas. Mas como teremos que rever a formatação do texto quando inserirmos as figuras artísticas, sugiro não gastarmos tanta energia nisso agora.

[livro_aluno.pdf](https://github.com/UmLivroAberto/livro/files/440889/livro_aluno.pdf)

**Comment by hjbortol** [comment]
Modifiquei o enunciado desta atividade da Lição 4:

https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#equivalencia_densidade_1

O aluno, no item (B), poderia dar como resposta 0, o que torna menos interessante o item (C).

**Comment by simas0** [comment]
Obrigado, @hjbortol!! 

Gente, vou colocar o prazo até amanhã (28/08) às 16h30 para colaborações na Introdução e para essa revisão deste issue porque depois eu preciso implementar as observações, gerar o pdf para impressão.

**Comment by simas0** [comment]
@hjbortol você mudou apenas o enunciado do item b) daquela questão?
