### ISSUE TITLE
2 no modo texto e 2 no modo matemático no LaTeX

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/fracoes_livro_piloto#114]
@simas0 , a fonte usada para números no ambiente matemático do LaTeX está diferente da fonte usada quando o número aparece como texto.

![modo-matematico](https://cloud.githubusercontent.com/assets/7694624/18034412/b128de80-6d12-11e6-97da-2e211247be98.jpg)

**Comment by gutosurrex** [comment]
Isso no pdf ou html?

**Comment by hjbortol** [comment]
No PDF!
