### ISSUE TITLE
Formatação do livro do professor em pdf

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#124]
O que precisamos é que ele tenha a mesma estruturação da Lição 1 no que diz respeito a:
-  Conter o título e o conteúdo do "Para o professor" inicial da Lição com a folha em uma única coluna no início da lição.
-  Negrito, sem alinhamento de parágrafo e inserir espaçamento vertical de .1cm depois do "Objetivos específicos: levar o aluno a" como abaixo:
  
  ```
  \noindent {\bf Objetivos específicos: Levar o aluno a} \vspace{.1cm}
  pular linha
  ```
-  O mesmo acima para "Recomendações e sugestões para o desenvolvimento da atividade:", mas além disso inserir também .1cm de espaçamento vertical antes do texto como abaixo:

```
\vspace{.1cm}

  \noindent {\bf Recomendações e sugestões para o desenvolvimento da atividade:} \vspace{.1cm}
pular linha
```
-  Procurar por itens que estejam expressos por (a) ou (A) ao invés de a), este último é o correto.
-  Retirar o alinhamento dos títulos "Atividade" e "Resposta da Atividade", isso deve ser feito no arquivo template.sty onde está o preâmbulo.

**Comment by simas0** [comment]
Os arquivos a serem alterados estão em:
[(https://github.com/simas0/Livro-Aberto-de-Matematica-texto-do-projeto-/tree/master/Latex)]

São os arquivos "capX_professor.tex" para X de 1 a 5.

**Comment by simas0** [comment]
Fiz os três primeiros itens acima e a segunda parte do último.
[livro_professor.pdf](https://github.com/UmLivroAberto/livro/files/478476/livro_professor.pdf)

**Comment by simas0** [comment]
Eu gostaria de sugestões para melhorar esteticamente o livro do professor.

**Comment by hjbortol** [comment]
Enquanto não se encontra uma solução para que o formato fique igual ao livro do professor espanhol e do Michel Spira, pensando um pouco, talvez o livro do professor poderia ser como está na plataforma: orientações, a atividade do aluno, as respostas.
