### ISSUE TITLE
Revisão da Introdução

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#125]
Caros, percebi que a introdução não diz, por exemplo, qual é a finalidade esperada de cada uma das seções: Explorando o Assunto, Organizando as Ideias, Refletindo, etc. 

Talvez seja bom falar um pouco do projeto também na introdução. Isso foi uma sugestão do Humberto, que eu não gostei na hora, mas agora acho melhor ter. O que vocês acham?

@hjbortol , poderia me ajudar com isso?

**Comment by hjbortol** [comment]
Vou tentar fazer um v0!
