### ISSUE TITLE
Título da Lição 2

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#128]
Algumas propostas:
(1) Mais frações da unidade
(2) Juntando frações da da unidade
(3) Frações gerais da unidade

O título atual é: **"Multiplicando a fração da unidade"**
by @hjbortol

**Comment by cydara** [comment]
Acho que trocar "Multiplicando" por "juntando" é sugerir que estão trocando a operção de multiplicação pela operação de adição. Que tal "Outras frações da unidade"?

**Comment by simas0** [comment]
Decidido (2).
