### ISSUE TITLE
Correções na lição 5 - quem pode abrir os pdfs e efetuar as alterações?

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#136]
Caros, eu implementei as correções nas Lições 1 e 2, a Letícia na Lição 3 e a Cydara na Lição 4. Acho justo que algum dos demais implementasse as alterações da Lição 5 no arquivo .tex.

Para ver as sugestões realizadas estão nos arquivos:
https://dl.dropboxusercontent.com/u/2371346/licao5/bruna_2016_nov_19_lic3_4_e_5.pdf
https://dl.dropboxusercontent.com/u/2371346/licao5/cydara_2016_nov_20.pdf
https://dl.dropboxusercontent.com/u/2371346/licao5/fracoes_v1_0_LET.PDF
https://dl.dropboxusercontent.com/u/2371346/licao5/humberto_2016_nov_18_lic5_e_reproducao.pdf
https://dl.dropboxusercontent.com/u/2371346/licao5/thatianne_2016_nov_20_lic3_e5.pdf

 Os arquivos a serem alterados são cap5_aluno.tex
https://github.com/livro-aberto/fracoes_livro_piloto/blob/master/tex/cap5_aluno.tex
 e cap5_professor.tex 
https://github.com/livro-aberto/fracoes_livro_piloto/blob/master/tex/cap5_professor.tex

Vou enviar uma solicitação por e-mail para Victor, Wanderley e Wellerson, para eles também terem a oportunidade de colaborar. Por favor, avise quem decidir tomar para si a tarefa. 

O prazo para conclusão é 3 de janeiro.

**Comment by hjbortol** [comment]
@simas0, para 3 de janeiro, sem chance!

**Comment by hjbortol** [comment]
Última forma: acho que consigo fazer os ajustes da parte do professor.

**Comment by hjbortol** [comment]
Terminei a maioria das correções da parte do professor do Capítulo 5. Ficaram, contudo, algumas pendências (existem observações da @cydara que não entendi e, assim, não implementei).

No arquivo PDF da @estelanunes que o Fábio indicou na primeira mensagem, não havia comentário algum para a Lição 5.

Por comodidade, anexo os arquivos PDF com os comentários todos juntos já com as correções que fiz removidas. Não fiz modificação alguma na parte do aluno.


[lição-05-humberto-e-cydara-aluno.pdf](https://github.com/livro-aberto/fracoes_livro_piloto/files/670132/licao-05-humberto-e-cydara-aluno.pdf)
[lição-05-humberto-e-cydara-professor.pdf](https://github.com/livro-aberto/fracoes_livro_piloto/files/670134/licao-05-humberto-e-cydara-professor.pdf)
[lição-05-teddy-e-thatianne.pdf](https://github.com/livro-aberto/fracoes_livro_piloto/files/670133/licao-05-teddy-e-thatianne.pdf)

**Comment by simas0** [comment]
Muito obrigado, Humberto! Pessoal, ainda temos a parte do estudante a ser alterada.

**Comment by simas0** [comment]
Eu fiz as mudanças. Estou gerando os PDFs e vou postar no site e subir para este repositório em breve. Também enviarei a nova versão para os pesquisadores da área.
