### ISSUE TITLE
Compilação do livro do aluno: figura ..//media/cap5/secoes/PNGs_licao_05/ativ1_fig01.png não disponível

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/fracoes_livro_piloto#137]
Ao tentar compilar o livro do aluno, vi que o capítulo 5 faz chamada a imagem

..//media/cap5/secoes/PNGs_licao_05/ativ1_fig01.png

que não está disponível.

**Comment by simas0** [comment]
Acho que eu estava fazendo o push do meu computador apenas do diretório que tem os arquivos .tex. Veja se agora estão presentes os arquivos que você precisa.

https://github.com/livro-aberto/fracoes_livro_piloto/tree/master/media/cap5/secoes/PNGs_licao_05
