### ISSUE TITLE
Atividade 2 da Lição 3 - alteração na imagem

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#138]
Caros, nestas revisões é muito importante fazer sugestões explícitas e não apenas levantar um problema porque alguém vai ter que pensar numa solução. O ideal é que a crítica venha com uma sugestão de alteração exata. 

Baseado nas ponderações de alguns de vocês sobre esta atividade, eu fiz as alterações na figura e no item b) incluí explicação dizendo que a parte clara foi retirada. A da direita é a nova, a da esquerda, a antiga. Isso resolve os problemas para vocês?

A fonte do texto está diferente, mas isso eu vou mudar depois, não se preocupem.

![screenshot from 2016-12-23 17-21-02](https://cloud.githubusercontent.com/assets/16407253/21461040/18a36944-c935-11e6-941e-b08479ea7447.png)

**Comment by hjbortol** [comment]
Para mim ficou bem melhor!
