### ISSUE TITLE
Introdução: "frações é" ou "frações são"

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/fracoes_livro_piloto#168]
Na introdução está escrito:

> Frações é certamente um dos tópicos que mais desafia o ensino e a aprendizagem na matemática da educação básica.

Uma dúvida: "frações é certamente ..." ou "frações são certamente ..."?

@simas0, @cydara, @estelanunes, @wmrezende

**Comment by cydara** [comment]
Eu alteraria para : "O assunto _frações_é..."

**Comment by simas0** [comment]
Acho que está correto no texto porque Frações é um tópico. Mas concordo que está estranho de ler (especialmente na primeira frase do livro hehe) e acho que a solução da Cydara parece excelente.

Alterei no Github, a próxima compilação atualizará o PDF, juntamente com o nome da Letícia na segunda capa e outras alterações menores que já aconteceram na segunda edição.
