### ISSUE TITLE
Organizando as ideias - Correção da figura de copos de suco de laranja

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#192]
Para o ilustrador: refazer a figura, deve ter apenas um copo. O conteúdo deve representar um terço do copo (isto é, um terço da altura do copo).

Usar linha tracejada na altura de um terço do copo e na altura de dois terços do copo.

![image](https://user-images.githubusercontent.com/16407253/78150032-1a212c80-740d-11ea-93f8-407219757e77.png)

**Comment by estelanunes** [comment]
PDF – p.17 

Por exemplo, se, em uma receita, é necessário acrescentar um terço de um litro de suco de laranja, isso significa que, para colocar a quantidade correta de suco na receita, é preciso repartir o litro de suco em três partes iguais e usar apenas uma dessas partes, que é um terço do litro de suco. Nesse caso, a unidade é um litro de suco de laranja. Imagine que no copo caiba 1 litro. 
 
Problema: 
O litro estar vinculado ao copo e ao suco. 

Condições:
1.	Tem que ser 1/3.
2.	Não pode ser comida. (Pensamos massinha de modelar) 
3.	Tem que envolver volume / capacidade. 
4.	Tem que “usar” apenas 1/3. (?)

Proposta 1 – Massinha de modelar (1,2 e 3 - Massa)
Por exemplo, se três irmãos quiserem repartir igualmente entre eles uma porção de massa de modelar, cada um ficará com um terço da quantidade de massinha. Para isso, podem dividir a massinha em três partes iguais e cada um ficar com uma dessas partes. Nesse caso a unidade é a porção de massa de modelar.            

Proposta 2 – (1,3 e 4) – Mantendo líquido - Leite
Por exemplo, se, para preparar uma receita, é necessário acrescentar um terço de um litro de leite, então para colocar a quantidade correta de leite na receita, é preciso repartir o litro de leite em três partes iguais e usar apenas uma dessas partes.  Nesse caso, cada uma das partes é um terço do litro de leite. A unidade é um litro de leite.

**Comment by simas0** [comment]
Gosto muito da ideia da massinha de modelar!

Só para atualizar que nós alteramos o texto desse parágrafo para 
![image](https://user-images.githubusercontent.com/16407253/78788036-9c679e80-7981-11ea-9ef3-6dcb3570a7d1.png)

**Comment by anapaulapereira** [comment]
![image](https://user-images.githubusercontent.com/63082895/78838439-921ec200-79cc-11ea-84b5-76b2c5b78b25.png)

**Comment by simas0** [comment]
Alterei o texto e criarei novo issue para a imagem.
