### ISSUE TITLE
Lição 1, Atividade 5 - É necessário rever o texto para o professor após alterações.

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#197]

**Comment by anapaulapereira** [comment]
Fique atento aos alunos que selecionarem as figuras que simplesmente possuem alguma associação com o número 3, não correspondendo a terços. Por exemplo, um aluno que associe a Figura f) a terços pode ainda não ter compreendido a necessidade da equipartição para a identificação de um terço. Já o aluno que associa Figura g) a terços pode estar simplesmente contando as partes em cinza, sem que tenha reconhecido que a figura deveria estar dividida em 3 partes iguais e não em 4.

**Comment by anapaulapereira** [comment]
A figura j) mencionada no texto anterior foi retirada na versão nova. É isso mesmo?
![Figura 1](https://user-images.githubusercontent.com/63082895/78610045-69ff5980-783a-11ea-8bdf-7da5885590ca.png)

**Comment by simas0** [comment]
> Fique atento aos alunos que selecionarem as figuras que simplesmente possuem alguma associação com o número 3, não correspondendo a terços. Por exemplo, um aluno que associe a Figura f) a terços pode ainda não ter compreendido a necessidade da equipartição para a identificação de um terço. Já o aluno que associa Figura g) a terços pode estar simplesmente contando as partes em cinza, sem que tenha reconhecido que a figura deveria estar dividida em 3 partes iguais e não em 4.

Oi Ana, você sugere que a gente inclua esta recomendação ao professor? Em caso afirmativo: em que posição dentre as novas recomendações, você sugere que seja incluída?

**Comment by simas0** [comment]
Obrigado, Ana! Este está resolvido! Abraço!
