### ISSUE TITLE
Lição 1 Atividade 4: palheta de cores que é universal (incluindo daltônicos)

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/fracoes_livro_piloto#203]
Aqui vai um arquivo com sugestões de palhetas:

[palheta-de-cores.pdf](https://github.com/livro-aberto/fracoes_livro_piloto/files/4440970/palheta-de-cores.pdf)

**Comment by simas0** [comment]
Feito! Fiquei receoso de alterar a opacidade das cores e perder o efeito para daltônicos. Ficou assim.

![image](https://user-images.githubusercontent.com/16407253/78796168-595ef880-798c-11ea-9281-d998f8926330.png)
