### ISSUE TITLE
Lição 1 - Atividade 6 Incluir mais uma opção de resposta

### ISSUE THREAD

**Issue by anapaulapereira** [livro-aberto/fracoes_livro_piloto#207]
Incluir esta opção como resposta no item (i) da Atividade 6

**Comment by anapaulapereira** [comment]
![Figura 2](https://user-images.githubusercontent.com/63082895/78836671-f63f8700-79c8-11ea-8656-4e4d85a195ae.png)

**Comment by simas0** [comment]
Feito!
