### ISSUE TITLE
Pontuação das seções "Objetivos específicos" e "Discussão sobre a atividade".

### ISSUE THREAD

**Issue by estelanunes** [livro-aberto/fracoes_livro_piloto#222]
É necessário uniformizar a pontuação, o uso de letras maiúsculas e os títulos dessas seções. 
Exemplo: 
1. Objetivos específicos: Levar o aluno a 
     ⋆ **R**econhecer ccsvftsdeferk;jerthnt.khtre.je
**Questão única**: VAMOS COMEÇAR O ITENS COM LETRAS MAIÚSCULAS OU MINÚSCULAS? Os dois tipos estão sendo usados nas diversas lições. 

2. Recomendações e sugestões para o desenvolvimento da atividade: 
     ⋆ Esta é uma atividaea xfcxvsaxsdg,j fyeheug
**Questões: a)** Análoga a anterior. Uso de letras maiúsculas ou minúsculas no início dos tópicos.
                 **b)** Em alguns o título ainda é "Recomendações e sugestões para o desenvolvimento da 
                      atividade". É necessário uniformizar.

**Comment by simas0** [comment]
Vamos manter as iniciais maiúsculas nos inícios de frases em todos os itens, tanto nos "Objetivos específicos" como nas "Discussões sobre o desenvolvimento da atividade" como nas Soluções das Atividades.

@tarsobcaldas cuida disso pra gente, por favor.
