### ISSUE TITLE
Ativ. 1 Lic. 3 - Refazer as figuras das caixas d'água

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#233]
Preciso que as figuras sejam refeitas em TikZ. Seguem alguns dos problemas das figuras:

![image](https://user-images.githubusercontent.com/16407253/85453519-537fb900-b572-11ea-82bd-a3a4967e5c2f.png)

![image](https://user-images.githubusercontent.com/16407253/85453554-61353e80-b572-11ea-8ba1-08197aa59e70.png)

 - Elas estão construídas com representação em perspectiva, o ideal é em projeção ortogonal.
 - A transparência precisa ser coerente. A aresta vertical do fundo do cubo precisa ser visível e também a mesinha de debaixo das caixas.
 - A mesa é necessária para que as escalas possam ser posicionadas.
 - As caixas deviam estar todas na mesma posição na mesa em ambas as figuras porque representam a mesma caixa sendo enchida. Observe que quando têm água, as caixas estão recuadas para o fundo da mesa.
 - Nas escalas, os traços de fração devem estar alinhados com as respectivas marcações nas escalas. 
 - As figuras devem ser inseridas em um quadro para parecerem quadrinhos.

**Comment by tarsobcaldas** [comment]
Figuras já colocadas no código do livro. O código em tikz está na pasta tikz dentro da pasta de figuras.
