### ISSUE TITLE
Mapa do Tesouro

### ISSUE THREAD

**Issue by simas0** [livro-aberto/fracoes_livro_piloto#235]
A figura atual é essa aqui:
![image](https://user-images.githubusercontent.com/16407253/86289328-e26b8180-bbc1-11ea-9306-e61e54bbc832.png)

Seguem as alterações necessárias para serem feitas em TiKz sobre a imagem de um mapa do tesouro.

1. O início da linha tracejada tem que começar depois da palmeira e bem perto dela.
2. Aumentar a faixa e reduzir a altura da faixa para que não chame tanto a atenção essa dimensão. Reduza a um terço ou um quarto da altura atual.
3. Usar uma figura aberta (marcada para reutilização e precisaremos dar crédito, então registre o dono) e incluir elementos em Tikz na figura.
4. Considere a possibilidade de dizer que as instruções estão no verso do mapa e, então, incluir outra figura, tipo um papiro com as instruções.
5. As duas últimas instruções da figura devem ser escritas em um único item que é "No mapa, os pontos que marcam os locais em que os baús estão enterrados ficam a ⅚ e a ⅝ da unidade, a partir da palmeira. A chave do baú com o tesouro está enterrada a 13/8  da unidade a partir da palmeira."
6. Incluir um último item: "O baú com o tesouro está mais distante da palmeira." 
7. A primeira instrução começa com "Há dois baús escondidos, um deles está carregado com um tesouro."

**Comment by simas0** [comment]
@estelanunes poderia conferir as instruções e, se quiser, sugira uma imagem de base.

**Comment by simas0** [comment]
Tarso, a Palmeira cumpre o papel de zero na reta numérica. Acho que é importante você resolver a Atividade antes de resolver.

**Comment by tarsobcaldas** [comment]
Figura já colocada no código do capítulo. As figuras para o código estão na pasta de figuras da lição 3 e o código em tikz na pasta tikz dentro da pasta de figuras.
