### ISSUE TITLE
Para o professor - Lição 5

### ISSUE THREAD

**Issue by estelanunes** [livro-aberto/fracoes_livro_piloto#86]
Os "Para o professor da Lição" ainda não foram adaptados ao mesmo formato dos das outras lições.

**Comment by simas0** [comment]
Na [Atividade 9 da Lição 5](https://www.umlivroaberto.com/livro/doku.php?id=cap5:texto#reta_mais) usa-se modelos de retas numéricas na vertical. Como isso não foi feito antes podemos alertar ao professor ou deitar as retinhas. Eu posso colocá-las na horizontal (estou fazendo as figuras da lição em Tikz agora)

**Comment by estelanunes** [comment]
Fábio, acho bom que a reta fique na vertical. Entendi que era uma decisão pedagógica do Victor e do Wellerson e que isso seria explicado ao professor nas orientações específicas, quando revisadas.

**Comment by victorgiraldoUFRJ** [comment]
Feito.
