### ISSUE TITLE
Atividade 1 da Lição 5

### ISSUE THREAD

**Issue by cydara** [livro-aberto/fracoes_livro_piloto#87]
Unidade 1:
Alertamos (Leticia e Cydara) para o fato de que, nesta atividade, está-se escolhendo uma unidade , sem particioná-la. Assim, a atividade tem seu mérito por resgatar as interpretações de juntar e de retirar sobre as operações de adição e subtração, respectivamente, e não de trabalhar-se com frações. Isto talvez fosse interessante de ser salientado ao professor.

**Comment by victorgiraldoUFRJ** [comment]
Alteramos o texto para o professor.
Victor e Wellerson

**Comment by cydara** [comment]
O terceiro objetivo continua não sendo alcançado, pois não se está particionando a unidade escolhida "copo". Sugiro que seja retirado
