### ISSUE TITLE
Atividade 6_Novinha_Li

### ISSUE THREAD

**Issue by estelanunes** [livro-aberto/fracoes_livro_piloto#90]
**Na reestruturação do "Para o Professor" rever a redação a do seguinte trecho:**
"A partir dessas explorações, a ideia é que os alunos percebam que há diversas formas de saber qual fita tem o maior tamanho, e que, além disso, é possível determinar o tamanho – ou a **medida** – da nova fita vermelha e azul em relação à original somando-se as medidas dos dois pedaços (vermelho e azul) que a compõe. Para isso, algumas observações são fundamentais:
      - O tamanho de uma fita original será uma **unidade** de medida, associada ao número 1, em relação a qual as medidas das demais grandezas serão determinadas, e expressas como frações.
      - Como os pedaços vermelho e azul correspondem a subdivisões de tamanhos diferentes da unidade de medida (tamanho da fita original), para determinar sua soma será preciso expressá-los como múltiplos inteiros de uma **subdivisão comum**, que pode ser obtida dividindo-se o pedaço vermelho em duas partes iguais e o pedaço azul em três partes iguais."

**Comment by victorgiraldoUFRJ** [comment]
Que aspecto da redação deve ser revisto?

**Comment by estelanunes** [comment]
Ficou combinado que não trataríamos de medida.
