### ISSUE TITLE
Atividade 8_ Calcule_ Lição 5

### ISSUE THREAD

**Issue by estelanunes** [livro-aberto/fracoes_livro_piloto#91]
Cydara e Leticia.

(i) Por que esta atividade não é incluída como um novo item da atividade 7? 

(ii) Se mantida como atividade, é necessário alterar o enunciado (ver comentário da Cydara de 18/07/2016: “Determine as soluções das contas a seguir.” não era um enunciado típico das atividades até o momento… Elas sempre procuraram uma contextualização convincente. Acho que a equipe deve discutir a manutenção de tal enunciado. Se forem favoráveis a eles, sugiro que, pelo menos, o aluno seja convidado a representar graficamente tais operações.)

**Comment by victorgiraldoUFRJ** [comment]
i) Na atividade 7 é pedida apenas a determinação de frações equivalente com um denominador comum. e na atividade 8 são pedidas as contas. Mas elas podem ser juntadas, tanto faz.
ii) A ideia era um pouco abstrair do contexto mesmo. Mas incluímos fazer o desenho no enunciado.
